//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by maestro.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_TARGFORM                    101
#define IDD_TRIALFORM                   102
#define IDB_SPLASH                      104
#define IDS_USRGUIDE_HOME               125
#define IDR_MAINFRAME                   128
#define IDR_CXPOPUPS                    131
#define IDD_POPUP                       136
#define IDD_CHANNELFORM                 137
#define IDB_CXICONS                     142
#define IDD_AIOCP                       146
#define IDD_CONTCP1                     148
#define IDD_TMRCP                       149
#define IDD_TRIALCP1                    150
#define IDD_TRIALCP2                    151
#define IDD_DISPLAY                     152
#define IDD_RUNFORM                     153
#define IDD_CONTCP2                     154
#define IDD_FIXREW                      155
#define IDD_PERTFORM                    156
#define IDD_MSGLOG                      157
#define IDI_TGT_ICON                    158
#define IDD_TRIALCP3                    158
#define IDI_TRIAL_ICON                  159
#define IDD_TRIALCP4                    159
#define IDI_CHAN_ICON                   160
#define IDD_RMVSTORE                    160
#define IDI_RUN_ICON                    161
#define IDD_EYELINK                     161
#define IDI_PERT_ICON                   162
#define IDD_TRIALFORM_RV                162
#define IDI_MAINAPP                     163
#define IDD_TRIALFORM_OTHER             163
#define IDD_TRIALFORM_MAIN              164
#define IDC_CH_RESTOREDEF               460
#define IDC_CH_SPACEEVENLY              461
#define IDC_CH_ONEAXIS                  462
#define IDC_CH_YMIN                     463
#define IDC_CH_YMAX                     464
#define IDC_CH_GRID                     465
#define IDC_POPUP_TREE                  1000
#define IDC_TARGF_MODMODE               1000
#define IDC_TARGF_TYPE                  1004
#define IDC_TARGF_SHAPE                 1005
#define IDC_TARGF_ORECTW                1010
#define IDC_TARGF_ORECTH                1011
#define IDC_TARGF_IRECTW                1012
#define IDC_TARGF_IRECTH                1013
#define IDC_TARGF_REDMEAN               1014
#define IDC_TARGF_GRNMEAN               1015
#define IDC_TARGF_BLUMEAN               1016
#define IDC_TARGF_REDCON                1017
#define IDC_TARGF_GRNCON                1018
#define IDC_TARGF_BLUCON                1019
#define IDC_TARGF_NDOTS                 1020
#define IDC_TARGF_DOTSZ                 1021
#define IDC_TARGF_DOTLIFE               1022
#define IDC_TARGF_COHER                 1023
#define IDC_TARGF_NOISERNG              1024
#define IDC_TARGF_NOISEUPD              1025
#define IDC_TARGF_GRAT1_DA              1026
#define IDC_TARGF_GRAT2_DA              1027
#define IDC_TARGF_GRAT1_SF              1028
#define IDC_TARGF_GRAT2_SF              1029
#define IDC_TARGF_GRAT1_PH              1030
#define IDC_TARGF_GRAT2_PH              1031
#define IDC_TARGF_XSIGMA                1032
#define IDC_TARGF_YSIGMA                1033
#define IDC_TARGF_RANDSEED              1034
#define IDC_TARGF_REDMEAN2              1035
#define IDC_TARGF_GRNMEAN2              1036
#define IDC_TARGF_BLUMEAN2              1037
#define IDC_TARGF_REDCON2               1038
#define IDC_TARGF_GRNCON2               1039
#define IDC_TARGF_BLUCON2               1040
#define IDC_TARGF_FLICKON               1041
#define IDC_TARGF_FLICKOFF              1042
#define IDC_TARGF_FLICKDELAY            1043
#define IDC_TARGF_MVFOLDER              1048
#define IDC_TARGF_MVFILE                1049
#define IDC_TARGF_GRAY                  1050
#define IDC_TARGF_DOTLF_MS              1051
#define IDC_TARGF_DOTLF_DEG             1052
#define IDC_TARGF_NOISEDIR              1053
#define IDC_TARGF_NOISESPEED            1054
#define IDC_TARGF_SINE                  1055
#define IDC_TARGF_SQUARE                1056
#define IDC_TARGF_INDEPGRATS            1057
#define IDC_TARGF_ORIENTADJ             1058
#define IDC_TARGF_SPDALG                1059
#define IDC_TARGF_MVREP                 1060
#define IDC_TARGF_MVPAUSE               1061
#define IDC_TARGF_MVRATE                1062
#define IDC_TARGF_WRTSCRN               1063
#define IDC_TARGF_WLBL                  1070
#define IDC_TARGF_ORLBL                 1072
#define IDC_TARGF_IRLBL                 1073
#define IDC_RF_DUTYPER                  1100
#define IDC_RF_AUTOSTOP                 1101
#define IDC_RF_HOFFSET                  1102
#define IDC_RF_VOFFSET                  1103
#define IDC_RF_DUTYPULSE                1104
#define IDC_RF_STIMULI                  1106
#define IDC_EL_XPOL                     1188
#define IDC_EL_YPOL                     1189
#define IDC_EL_CONNECT                  1190
#define IDC_EL_XOFS_RO                  1191
#define IDC_EL_XGAIN_RO                 1192
#define IDC_EL_YOFS_RO                  1193
#define IDC_EL_YGAIN_RO                 1194
#define IDC_EL_XOFS_SLIDE               1195
#define IDC_EL_YOFS_SLIDE               1196
#define IDC_EL_XGAIN_SLIDE              1197
#define IDC_EL_YGAIN_SLIDE              1198
#define IDC_EL_VELFW                    1199
#define IDC_RMV_FOLDERLIST              1200
#define IDC_RMV_FILELIST                1201
#define IDC_RMV_SRC                     1210
#define IDC_RMV_FOLDER                  1211
#define IDC_RMV_FILE                    1212
#define IDC_RMV_DELFOLDER               1220
#define IDC_RMV_DELFILE                 1221
#define IDC_RMV_DOWNLOAD                1222
#define IDC_TRH_WTSPIN                  1300
#define IDC_TRH_SAVESEGSPIN             1301
#define IDC_TRH_FAILSAFESPIN            1302
#define IDC_TRH_SPECSEGSPIN             1303
#define IDC_TRH_MARK1SPIN               1305
#define IDC_TRH_MARK2SPIN               1306
#define IDC_TRH_SGMSEGSPIN              1307
#define IDC_TRH_SAVESEG                 1321
#define IDC_TRH_FAILSAFE                1322
#define IDC_TRH_SPECSEG                 1323
#define IDC_TRH_MARK1                   1325
#define IDC_TRH_MARK2                   1326
#define IDC_TRH_SGMSEG                  1327
#define IDC_TRH_CHCFG                   1340
#define IDC_TRH_SGMOP                   1341
#define IDC_TRH_SEGTABLE                1350
#define IDC_TRH_PARTITIONS              1351
#define IDC_TRH_PERTS                   1352
#define IDC_TRV_GRID                    1353
#define IDC_TRH_KEEP                    1380
#define IDC_TRH_SPECOP                  1381
#define IDC_TRH_TRITYP                  1382
#define IDC_TRH_STAIRRESP               1383
#define IDC_TRH_MTRMODE                 1384
#define IDC_TRH_SGMTRIG                 1385
#define IDC_TRH_IGNPOSSCALE             1386
#define IDC_TRH_IGNPOSROT               1387
#define IDC_TRH_IGNVELSCALE             1388
#define IDC_TRH_IGNVELROT               1389
#define IDC_TRH_SACCVT                  1390
#define IDC_TRH_STAIRSTREN              1391
#define IDC_TRH_REWP1                   1392
#define IDC_TRH_REWP2                   1393
#define IDC_TRH_MTRINTV                 1394
#define IDC_TRH_MTRLEN                  1395
#define IDC_TRH_WEIGHT                  1396
#define IDC_TRH_WHVR1NUM                1398
#define IDC_TRH_WHVR1DEN                1399
#define IDC_TRH_WHVR2NUM                1400
#define IDC_TRH_WHVR2DEN                1401
#define IDC_TRH_SGMPA1                  1410
#define IDC_TRH_SGMPA2                  1411
#define IDC_TRH_SGMPW1                  1412
#define IDC_TRH_SGMPW2                  1413
#define IDC_TRH_SGMIPI                  1414
#define IDC_TRH_SGMITI                  1415
#define IDC_TRH_SGMNP                   1416
#define IDC_TRH_SGMNT                   1417
#define IDC_TRH_TABPROPS                1420
#define IDC_AIO_CHANS                   1500
#define IDC_AIO_UNITS                   1501
#define IDC_AIO_PAUSE                   1502
#define IDC_AIO_AICAL                   1503
#define IDC_AIO_CHLIST                  1504
#define IDC_TMR_CHANS                   1520
#define IDC_TMR_RESET                   1521
#define IDC_TMR_LOOP                    1522
#define IDC_TMR_REPEAT                  1523
#define IDC_TRIAL_GO                    1600
#define IDC_TRIAL_ABORT                 1601
#define IDC_TRIAL_ATT                   1602
#define IDC_TRIAL_REW                   1603
#define IDC_TRIAL_BLK                   1604
#define IDC_TRIAL_RECDATA               1605
#define IDC_TRIAL_RECSPKS               1606
#define IDC_TRIAL_PAUSE                 1607
#define IDC_TRIAL_PRES                  1608
#define IDC_TRIAL_DATAPATH              1615
#define IDC_TRIAL_DELAY                 1616
#define IDC_TRIAL_STOP_COUNT            1617
#define IDC_TRIAL_IGT                   1618
#define IDC_TRIAL_ATT_RO                1619
#define IDC_TRIAL_REW_RO                1620
#define IDC_TRIAL_BLK_RO                1621
#define IDC_TRIAL_PRES_RO               1622
#define IDC_TRIAL_SET                   1630
#define IDC_TRIAL_CURR                  1631
#define IDC_TRIAL_SEQ_SUBSETS           1632
#define IDC_TRIAL_SEQ_TRIALS            1633
#define IDC_TRIAL_STOP_MODE             1634
#define IDC_TRIAL_STAIR_STREN           1650
#define IDC_TRIAL_STAIR_IRREL           1651
#define IDC_TRIAL_POS_SCALE             1652
#define IDC_TRIAL_POS_ROT               1653
#define IDC_TRIAL_VEL_SCALE             1654
#define IDC_TRIAL_VEL_ROT               1655
#define IDC_TRIAL_START_H               1656
#define IDC_TRIAL_START_V               1657
#define IDC_TRIAL_VSTABWIN              1658
#define IDC_TRIAL_CHAINLEN              1659
#define IDC_TRIAL_STAIR_REV             1660
#define IDC_TRIAL_STAIR_UP              1661
#define IDC_TRIAL_STAIR_DN              1662
#define IDC_TRIAL_STAIR_REVBUDDY        1663
#define IDC_TRIAL_STAIR_UPBUDDY         1664
#define IDC_TRIAL_STAIR_DNBUDDY         1665
#define IDC_TRIAL_CH_ENA                1667
#define IDC_TRIAL_CHCFG                 1668
#define IDC_TRIAL_RSTPARMS              1670
#define IDC_TSTAT_SET                   1680
#define IDC_TSTAT_GRID                  1681
#define IDC_CONT_GO                     1700
#define IDC_CONT_RESTART                1701
#define IDC_CONT_ABORT                  1702
#define IDC_CONT_REC                    1703
#define IDC_CONT_FIXATE                 1704
#define IDC_CONT_SET                    1705
#define IDC_CONT_CURR                   1706
#define IDC_CONT_EXECMODE               1707
#define IDC_CONT_CHANCFG                1708
#define IDC_CONT_DATAPATH               1710
#define IDC_CONT_RECSPKS                1712
#define IDC_CONT_TGT_ADD                1726
#define IDC_CONT_TGT_DEL                1727
#define IDC_CONT_TGT_CLEAR              1728
#define IDC_CONT_TGTS                   1730
#define IDC_FIX_DUR                     1800
#define IDC_FIX_HACC                    1801
#define IDC_FIX_VACC                    1802
#define IDC_FIX_REW1                    1803
#define IDC_FIX_REW2                    1804
#define IDC_FIX_VRATIO                  1805
#define IDC_FIX_AUDIOREW                1806
#define IDC_FIX_REWMULT                 1807
#define IDC_FIX_NREWARDS                1808
#define IDC_FIX_REWARDSUM               1809
#define IDC_FIX_REWOVR                  1810
#define IDC_FIX_REWBEEP                 1811
#define IDC_FIX_RESETREW                1812
#define IDC_DISP_FB_DIST                1906
#define IDC_DISP_FB_W                   1907
#define IDC_DISP_FB_H                   1908
#define IDC_DISP_FB_RED                 1909
#define IDC_DISP_FB_GRN                 1910
#define IDC_DISP_FB_BLU                 1911
#define IDC_DISP_GAMMA_R                1912
#define IDC_DISP_GAMMA_G                1913
#define IDC_DISP_GAMMA_B                1914
#define IDC_DISP_SYNCDUR                1915
#define IDC_DISP_SYNCSZ                 1916
#define IDC_DISP_FBFIELD                1921
#define IDC_DISP_RMVMODE                1925
#define IDC_DISP_FB_GRAY                1932
#define IDC_PERT_GRID                   2000
#define IDC_RPD_CURR                    2000
#define IDC_RPD_RESPTYPE                2001
#define IDC_RPD_VIEW                    2002
#define IDC_RPD_REW_ENA                 2010
#define IDC_RPD_NEWDIST                 2011
#define IDC_RPD_SAVE                    2012
#define IDC_RPD_REWMIN                  2020
#define IDC_RPD_REWMAX                  2021
#define IDC_RPD_REWSHIFT                2022
#define IDC_RPD_REWNUPD                 2023
#define IDC_RPD_RNG_MIN                 2024
#define IDC_RPD_RNG_MAX                 2025
#define IDC_RPD_CURRMOSTREC             2026
#define IDC_RPD_PREVMOSTREC             2027
#define IDC_RPD_CURRMEAN                2030
#define IDC_RPD_PREVMEAN                2031
#define IDC_RPD_REWSTATCURR             2032
#define IDC_RPD_REWSTATALL              2033
#define IDC_MSGLOG_SAVE                 2100
#define IDC_MSGLOG_PATH                 2101
#define IDC_MSGLOG_LOG                  2102
#define ID_VIEW_PLOTPANEL               32800
#define ID_VIEW_DATAPANEL               32801
#define ID_VIEW_LOGPANEL                32802
#define ID_VIEW_HISTPANEL               32803
#define ID_OBJ_FBTGT                    32821
#define ID_OBJ_TRIAL                    32822
#define ID_OBJ_CHCFG                    32823
#define ID_OBJ_RUN                      32824
#define ID_OBJ_PERT                     32825
#define ID_OBJ_TGSET                    32826
#define ID_OBJ_TRSET                    32827
#define ID_OBJ_TRSUB                    32828
#define ID_OBJ_RUNSET                   32829
#define ID_OBJ_COPY                     32830
#define ID_OBJ_NAME                     32831
#define ID_OBJ_DEL                      32832
#define ID_OBJ_CLEAR                    32833
#define ID_OBJ_PROP                     32834
#define ID_GRID_INSERTTARG              32840
#define ID_GRID_INSERTSEG               32841
#define ID_GRID_COPYSEG                 32842
#define ID_GRID_CUTSEG                  32843
#define ID_GRID_PASTESEG                32844
#define ID_GRID_REPLACESEG              32845
#define ID_GRID_REMOVESECT              32846
#define ID_GRID_DEL                     32847
#define ID_GRID_CLRTARGS                32848
#define ID_GRID_CLRSEGS                 32849
#define ID_GRID_CLRALL                  32850
#define ID_GRID_MODIFY                  32851
#define ID_GRID_MODALLSEGS              32852
#define ID_GRID_MODMATCHSEGS            32853
#define ID_GRID_MODALLTRIALS            32854
#define ID_GRID_MODMATCHTRIALS          32855
#define ID_GRID_MODSELTRIALS            32856
#define ID_PERT_APPEND                  32857
#define ID_PERT_REMOVE                  32858
#define ID_PERT_CLEAR                   32859
#define ID_MODE_IDLE                    32860
#define ID_MODE_TRIALS                  32861
#define ID_MODE_CONT                    32862
#define ID_MODE_TEST                    32863
#define ID_MODE_RESTART                 32864
#define ID_TESTAO_ZERO                  32870
#define ID_TESTAO_MAX                   32871
#define ID_TESTAO_MIN                   32872
#define ID_TESTAO_THIS                  32873
#define ID_TESTAO_WAVE                  32874
#define ID_OPT_CHAIR                    32875
#define ID_OPT_RMVDUPE                  32876
#define ID_RUN_STIM_CLEAR               32880
#define ID_RUN_STIM_COPY                32881
#define ID_RUN_STIM_CUT                 32882
#define ID_RUN_STIM_DEL                 32883
#define ID_RUN_STIM_PASTE               32884
#define ID_RUN_STIM_INS                 32885
#define ID_RUN_STIM_APPEND              32886
#define ID_HELP_USRGUIDE                33007
#define ID_FILE_COPYREMOTE              33008
#define IDS_COPYREMOTE_FILEDLGTITLE     33008
#define ID_CM_TOGGLEFIX                 33010
#define ID_CM_TOGGLETRACK               33011
#define ID_TM_TOGGLESTART               33012
#define ID_TM_TOGGLEPAUSE               33013
#define ID_CM_TRKSPEEDUP                33014
#define ID_CM_TRKSPEEDDN                33015
#define ID_CM_TRKDIRUP                  33016
#define ID_CM_TRKDIRDN                  33017
#define ID_FILE_JMXIMPORT               33018
#define ID_TARGF_MODTHIS                33020
#define ID_TARGF_MODALL                 33021
#define ID_TARGF_MODMATCHING            33022
#define ID_TARGF_MODSELECTED            33023

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        173
#define _APS_NEXT_COMMAND_VALUE         33020
#define _APS_NEXT_CONTROL_VALUE         1212
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
